### PR TITLE
Encoder

### PR DESCRIPTION
**Pull request by eric-wieser**
This has some other related fixes...

Uses the encoder library that comes with teensyduino

### CODE REVIEW

**Comment by mitchgu** [comment]
Sweet, looks awesome. Will merge once I get the time to test it. Have you written the pyHost stuff for this yet?

**Comment by eric-wieser** [comment]
Yes, but I haven't tested it yet, and it's built over the six change (#6).
Will push when ready

**Comment by mitchgu** [comment]
Hmm the angle bracket include for Encoder.h doesn't find the encoder library for me, probably because the file itself is Encoder.h. Did you copy the teensyduino Encoder library to the libraries folder, and did you have to adjust the makefile?

**Comment by eric-wieser** [comment]
No, I didn't, because I'm using windows, and Arduino looks for libraries only in the installation directory. So unfortunately, there's no good way to make libraries in `/libraries` be respected by windows.

Feel free to copy the library in there and adjust the makefile yourself though

**Pull request merged**
