### PR TITLE
Import teensy cores and libraries as submodules

### PR DESCRIPTION
**Pull request by mitchgu**
This only affects building using the makefile. Using the Arduino IDE should still be supported, provided one has installed Teensyduino and the necessary libraries. 

The motivation for this change is to be able to use a fork of the teensy3 cores that has more usb buffers, so as to support larger sliding window sizes. (See https://github.com/mitchgu/TAMProxy-pyHost/issues/24)

A nice side effect is that the build directory is now neater because all the extra libraries are in relative paths.

Unfortunately, eliminating the Teensyduino/Arduino IDE dependency altogether is still difficult because of Windows makefile support and the size, complexity, and platform dependency of the arm compilers.

### CODE REVIEW

**Comment by mitchgu** [comment]
I'm mainly waiting on actual testing with all the devices before I merge this.

**Comment by eric-wieser** [comment]
Why did windows support get dropped? I could conceivably get mingw in a state to compile this with the old makefil

**Comment by mitchgu** [comment]
The code that was in there was pretty minimal and never worked in the first place, so I figured it'd be better to remove it and raise an error until someone (maybe you) figures out a proper way to do it.

**Comment by eric-wieser** [comment]
Is this makefile your creation, or did it come from somewhere upstream?

**Comment by mitchgu** [comment]
It's derived from https://github.com/apmorton/teensy-template, which also did not support Windows

**Pull request merged**
