### PR TITLE
Adds support for servo devices.

### PR DESCRIPTION
**Pull request by reilleya**
Note: This includes the servo library using angle brackets.

### CODE REVIEW

**Comment by reilleya** [comment]
Are there any issues with this? It is needed for servos to function.

**Comment by mitchgu** [comment]
Yeah sorry I just haven't tested it yet, and I want to check the angle bracket compatibility thing.

**Comment by mitchgu** [comment]
Hey have you guys experienced the problem where running the servo_write example multiple times without powering off the teensy messes up the microsecond range to the point where the servo is stuck on one side? Restarting the teensy makes it work normally again.

**Comment by mitchgu** [comment]
Ok, I realized the servo needs to be detached from a  pin before the pwm pin can be used properly again. pushing the fix shortly.

**Pull request merged**
